
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MF
 */
public class Daftar_Pembelian extends javax.swing.JFrame {
    Connection con;
    Statement sta;
    ResultSet rs;
    DefaultTableModel tbm;
    /**
     * Creates new form Daftar_Pembelian
     */
    public Daftar_Pembelian() {
        initComponents();
        
        btnedit.setBackground(Color.black);
        btncancel.setBackground(Color.black);
        btnhapus.setBackground(Color.black);
        
        txtid_detail_pembelian.setEditable(false);
        txtid_supplier.setEditable(false);
        txtkode_barang.setEditable(false);
        
        btnback.setContentAreaFilled(false);
        
        jTable2.getTableHeader().setDefaultRenderer(new Supplier.HeaderColor());
        
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
          setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        sta = DB.stm;
        
        
        merk();
        supplier();
    }

    public JLabel getid_detail_pembelian() {
        return lblno_pembelian;
    }
    
    private void masuktable() {
        try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("ID DETAIL");
                tbm.addColumn("ID SUPPLIER");
                tbm.addColumn("NAMA SUPPLIER");
                tbm.addColumn("KODE BARANG");
                tbm.addColumn("NAMA BARANG");
                tbm.addColumn("QTY");
                tbm.addColumn("HARGA");
                
                jTable2.setModel(tbm);
                rs = sta.executeQuery("SELECT detail_pembelian.*,suku_cadang.kode_barang,suku_cadang.nm_suku_cadang,supplier.* FROM detail_pembelian,supplier,suku_cadang WHERE detail_pembelian.id_supplier = supplier.id_supplier AND suku_cadang.kode_barang = detail_pembelian.kode_barang AND detail_pembelian.no_pembelian='" + lblno_pembelian.getText() + "'");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("id_detail_pembelian"),
                    rs.getString("id_supplier"),
                    rs.getString("nm_supplier"),
                    rs.getString("kode_barang"),
                    rs.getString("nm_suku_cadang"),
                    rs.getString("qty"),
                    rs.getString("pembayaran"),
                    
                    
                });
                    jTable2.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    private void supplier() {
        try {
            String sql;
            sql = ("SELECT * FROM supplier ORDER BY nm_supplier ASC");
            rs = sta.executeQuery(sql);
            while (rs.next()) {
                cmbsupplier.addItem(rs.getString("nm_supplier"));
                
            } 
        } catch (Exception e) {
        }
    }
    
    private void merk() {
        try {
            String sql;
            sql = ("SELECT * FROM suku_cadang ORDER BY nm_suku_cadang ASC");
            rs = sta.executeQuery(sql);
            while (rs.next()) {
                cmbnama_barang.addItem(rs.getString("nm_suku_cadang"));
                
            } 
        } catch (Exception e) {
        }
    }
    
    private void kosong() {
        txtid_detail_pembelian.setText("");
        txtid_supplier.setText("");
        txtkode_barang.setText("");
        txtqty.setText("");
        txtharga.setText("");
        cmbnama_barang.setSelectedItem("----PILIHAN----");
        cmbsupplier.setSelectedItem("----PILIHAN----");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid_detail_pembelian = new javax.swing.JTextField();
        txtid_supplier = new javax.swing.JTextField();
        txtkode_barang = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        cmbsupplier = new javax.swing.JComboBox();
        cmbnama_barang = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblno_pembelian = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 614));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR BARANG PEMBELIAN");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID DETAIL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KODE BARANG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA BARANG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID SUPPLIER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA SUPPLIER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QTY.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HARGA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel5.add(jLabel9, gridBagConstraints);

        txtid_detail_pembelian.setBackground(new java.awt.Color(0, 0, 0));
        txtid_detail_pembelian.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtid_detail_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        txtid_detail_pembelian.setPreferredSize(new java.awt.Dimension(208, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(txtid_detail_pembelian, gridBagConstraints);

        txtid_supplier.setBackground(new java.awt.Color(0, 0, 0));
        txtid_supplier.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtid_supplier.setForeground(new java.awt.Color(255, 255, 255));
        txtid_supplier.setPreferredSize(new java.awt.Dimension(208, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(txtid_supplier, gridBagConstraints);

        txtkode_barang.setBackground(new java.awt.Color(0, 0, 0));
        txtkode_barang.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtkode_barang.setForeground(new java.awt.Color(255, 255, 255));
        txtkode_barang.setPreferredSize(new java.awt.Dimension(208, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(txtkode_barang, gridBagConstraints);

        txtqty.setBackground(new java.awt.Color(0, 0, 0));
        txtqty.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtqty.setForeground(new java.awt.Color(255, 255, 255));
        txtqty.setPreferredSize(new java.awt.Dimension(208, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(txtqty, gridBagConstraints);

        txtharga.setBackground(new java.awt.Color(0, 0, 0));
        txtharga.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtharga.setForeground(new java.awt.Color(255, 255, 255));
        txtharga.setPreferredSize(new java.awt.Dimension(208, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(txtharga, gridBagConstraints);

        cmbsupplier.setBackground(new java.awt.Color(0, 0, 0));
        cmbsupplier.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        cmbsupplier.setForeground(new java.awt.Color(255, 255, 255));
        cmbsupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----PILIHAN----" }));
        cmbsupplier.setPreferredSize(new java.awt.Dimension(208, 35));
        cmbsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsupplierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(cmbsupplier, gridBagConstraints);

        cmbnama_barang.setBackground(new java.awt.Color(0, 0, 0));
        cmbnama_barang.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        cmbnama_barang.setForeground(new java.awt.Color(255, 255, 255));
        cmbnama_barang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----PILIHAN----" }));
        cmbnama_barang.setPreferredSize(new java.awt.Dimension(208, 35));
        cmbnama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnama_barangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel5.add(cmbnama_barang, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(453, 100));

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(300, 100));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clipboard125.png"))); // NOI18N
        jPanel6.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        lblno_pembelian.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblno_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        lblno_pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping.png"))); // NOI18N
        lblno_pembelian.setText("jLabel10");
        lblno_pembelian.setPreferredSize(new java.awt.Dimension(100, 42));
        jPanel7.add(lblno_pembelian);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnedit.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette-outline-with-rounded-edges.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel3.add(btnedit);

        btnhapus.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhapusMouseExited(evt);
            }
        });
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus);

        btncancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelMouseExited(evt);
            }
        });
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        masuktable();
    }//GEN-LAST:event_formWindowActivated

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        txtid_detail_pembelian.setText(tbm.getValueAt(jTable2.getSelectedRow(), 0)+"");
        txtid_supplier.setText(tbm.getValueAt(jTable2.getSelectedRow(), 1)+"");
        cmbsupplier.setSelectedItem(tbm.getValueAt(jTable2.getSelectedRow(), 2)+"");
        txtkode_barang.setText(tbm.getValueAt(jTable2.getSelectedRow(), 3)+"");
        cmbnama_barang.setSelectedItem(tbm.getValueAt(jTable2.getSelectedRow(), 4)+"");
        txtqty.setText(tbm.getValueAt(jTable2.getSelectedRow(), 5)+"");
        txtharga.setText(tbm.getValueAt(jTable2.getSelectedRow(), 6)+"");
    }//GEN-LAST:event_jTable2MouseClicked

    private void cmbsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsupplierActionPerformed
         try {
            String sql;
            sql="SELECT * FROM supplier WHERE nm_supplier = '" + cmbsupplier.getSelectedItem() + "'";
            rs = sta.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("id_supplier");
                    txtid_supplier.setText(kode);
                }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbsupplierActionPerformed

    private void cmbnama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnama_barangActionPerformed
         try {
            String sql;
            sql="SELECT * FROM suku_cadang WHERE nm_suku_cadang = '" + cmbnama_barang.getSelectedItem() + "'";
            rs = sta.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("kode_barang");
                    txtkode_barang.setText(kode);
                }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmbnama_barangActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Yakin Ingin Menghapus Data", "HAPUS DATA",
            JOptionPane.YES_NO_OPTION);
        //dibuat untuk melakukan konfirmasi
        if (confirmed == JOptionPane.YES_OPTION) {
        try {
            String sql2 = "SELECT COUNT(*) AS 'jumlah' FROM detail_pembelian WHERE no_pembelian='" +lblno_pembelian.getText()+ "'";
            rs = sta.executeQuery(sql2);
            
            if(rs.next()) {
                String jumlah = rs.getString("jumlah");
                int jumlah2 = Integer.parseInt(jumlah);
                
                if (jumlah2 == 1) {
                    
                    int confirmed2 = JOptionPane.showConfirmDialog(null,
                                        "Yakin Ingin Menghapus Data Pembelian", "HAPUS DATA",
                                            JOptionPane.YES_NO_OPTION);
        
                    if (confirmed2 == JOptionPane.YES_OPTION) {
                        
                    String sql = "DELETE FROM detail_pembelian WHERE id_detail_pembelian = '" +txtid_detail_pembelian.getText()+ "'";
                    sta.executeUpdate(sql);
                    String sql3 = "DELETE FROM pembelian_barang WHERE no_pembelian = '" +lblno_pembelian.getText()+ "'";
                    sta.executeUpdate(sql3);
                    
                    this.dispose();
                    
                    }
                }
                
                else if (jumlah2 > 1) {
                    
                    
                    String sql6 = "DELETE FROM detail_pembelian WHERE id_detail_pembelian = '" +txtid_detail_pembelian.getText()+ "'";
                    sta.executeUpdate(sql6);
                    
                    String sql10 = "SELECT SUM(pembayaran) AS 'total' FROM detail_pembelian WHERE no_pembelian='" + lblno_pembelian.getText() + "'";
                    
                    rs = sta.executeQuery(sql10);
                    
                    if(rs.next()) {
                        rs.getString("total");
                        String sql7 = "UPDATE pembelian_barang SET pembayaran=total WHERE no_pembelian='" +lblno_pembelian.getText()+ "'";
                        sta.executeUpdate(sql7);
                        JOptionPane.showMessageDialog(rootPane, "BERHASIL");
                    }
                        
                    
                }
            }
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
         int confirmed = JOptionPane.showConfirmDialog(null,
            "Yakin Ingin Merubah Data", "EDIT DATA",
            JOptionPane.YES_NO_OPTION);
        //dibuat untuk melakukan konfirmasi
        if (confirmed == JOptionPane.YES_OPTION) {
            try {
                String sql;
                sql = ("UPDATE detail_pembelian set id_supplier='" +txtid_supplier.getText()+ "', kode_barang = '" +txtkode_barang.getText()+ "', qty = '" +txtqty.getText()+ "', pembayaran = '" +txtharga.getText()+ "' WHERE id_detail_pembelian='" +txtid_detail_pembelian.getText()+ "'");
                sta.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "BERHASIL DIUBAH");

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        btnedit.setText("EDIT");
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        btnedit.setText("");
    }//GEN-LAST:event_btneditMouseExited

    private void btnhapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseEntered
        btnhapus.setText("HAPUS");
    }//GEN-LAST:event_btnhapusMouseEntered

    private void btnhapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseExited
        btnhapus.setText("");
    }//GEN-LAST:event_btnhapusMouseExited

    private void btncancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseEntered
        btncancel.setText("REFRESH");
    }//GEN-LAST:event_btncancelMouseEntered

    private void btncancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseExited
        btncancel.setText("");
    }//GEN-LAST:event_btncancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox cmbnama_barang;
    private javax.swing.JComboBox cmbsupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblno_pembelian;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid_detail_pembelian;
    private javax.swing.JTextField txtid_supplier;
    private javax.swing.JTextField txtkode_barang;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
static public class HeaderColor extends DefaultTableCellRenderer {
       public HeaderColor(){
           setOpaque(true);
       }   
       public Component getTableCellRendererComponent(JTable jTable2, Object value, boolean selected, boolean focused, int row, int column) { 
        super.getTableCellRendererComponent(jTable2, value, selected, focused, row, column);
           setBackground(Color.black);
           return this;
       }
    }
}
