
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MF
 */
public class Edit_Barang_Transaksi extends javax.swing.JFrame {
    private Dimension screensize;
    Connection con;
    Statement sta;
    ResultSet rs;
    DefaultTableModel tbm;
    /**
     * Creates new form Edit_Barang_Transaksi
     */
    public Edit_Barang_Transaksi() {
        initComponents();
        
        btnback.setContentAreaFilled(false);
        btncancel.setBackground(Color.black);
        btnedit.setBackground(Color.black);
        btnhapus.setBackground(Color.black);
        
        txtkode_barang.setEditable(false);
        txtharga.setEditable(false);
        txtnama_barang.setEditable(false);
        
        screensize = Toolkit.getDefaultToolkit().getScreenSize();
          setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
        
         jTable2.getTableHeader().setDefaultRenderer(new Supplier.HeaderColor());  
          
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        sta = DB.stm;
        
        masuktable_suku();
              
    }

    private void kosong() {
         txtkode_barang.setText("");
         txtnama_barang.setText("");
         txtharga.setText("");
         txtqty.setText("");
         txtstock.setText("");
     }
    
   public JTextField gettxtqty() {
        return txtqty;
    }
   
   public JLabel getlblkode_barang_() {
       return lblkode;
   }
   
   public JTextField gettxtharga() {
       return txtharga;
   }
   
    public JLabel getlblid_detail_transaksi() {
        return lblid_detail_transaksi;
    }
    
    public JTextField gettxtkode_barang() {
        return txtkode_barang;
    }
    
    public JTextField gettxtnama_barang() {
        return txtnama_barang;
    }
    
    public JTextField gettxtstock() {
        return txtstock;
    }
    
    private void masuktable_suku() {
        try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("KODE BARANG");
                tbm.addColumn("NAMA BARANG");
                tbm.addColumn("MERK");
                tbm.addColumn("JENIS");
                tbm.addColumn("STOCK");
                tbm.addColumn("HARGA");
                tbm.addColumn("KET");
                
               jTable2.setModel(tbm);
                rs = sta.executeQuery("SELECT suku_cadang.*,merk_barang.id_merk,merk_barang.nm_merk FROM suku_cadang,merk_barang WHERE suku_cadang.id_merk=merk_barang.id_merk AND nm_suku_cadang LIKE '%" +txtcari.getText()+ "%'");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("kode_barang"),
                    rs.getString("nm_suku_cadang"),
                    rs.getString("nm_merk"),
                    rs.getString("jenis_suku_cadang"),
                    rs.getString("stock"),
                    rs.getString("harga"),
                    rs.getString("ket"),
                    
                    
                });
                    jTable2.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblid_detail_transaksi = new javax.swing.JLabel();
        lblkode = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkode_barang = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnama_barang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel7.add(btnback);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD BARANG");
        jPanel7.add(jLabel1);

        jPanel1.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        lblid_detail_transaksi.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblid_detail_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        lblid_detail_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock.png"))); // NOI18N
        lblid_detail_transaksi.setText("jLabel5");
        lblid_detail_transaksi.setPreferredSize(new java.awt.Dimension(100, 45));
        jPanel8.add(lblid_detail_transaksi);

        lblkode.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblkode.setForeground(new java.awt.Color(255, 255, 255));
        lblkode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user32.png"))); // NOI18N
        lblkode.setText("jLabel5");
        lblkode.setPreferredSize(new java.awt.Dimension(100, 45));
        jPanel8.add(lblkode);

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE BARANG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QTY.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HARGA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(jLabel4, gridBagConstraints);

        txtkode_barang.setBackground(new java.awt.Color(0, 0, 0));
        txtkode_barang.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtkode_barang.setForeground(new java.awt.Color(255, 255, 255));
        txtkode_barang.setPreferredSize(new java.awt.Dimension(235, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel4.add(txtkode_barang, gridBagConstraints);

        txtqty.setBackground(new java.awt.Color(0, 0, 0));
        txtqty.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtqty.setForeground(new java.awt.Color(255, 255, 255));
        txtqty.setPreferredSize(new java.awt.Dimension(235, 30));
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtyKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel4.add(txtqty, gridBagConstraints);

        txtharga.setBackground(new java.awt.Color(0, 0, 0));
        txtharga.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtharga.setForeground(new java.awt.Color(255, 255, 255));
        txtharga.setPreferredSize(new java.awt.Dimension(235, 30));
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthargaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel4.add(txtharga, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA BARANG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(jLabel7, gridBagConstraints);

        txtnama_barang.setBackground(new java.awt.Color(0, 0, 0));
        txtnama_barang.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtnama_barang.setForeground(new java.awt.Color(255, 255, 255));
        txtnama_barang.setPreferredSize(new java.awt.Dimension(235, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel4.add(txtnama_barang, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STOCK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel4.add(jLabel8, gridBagConstraints);

        txtstock.setBackground(new java.awt.Color(0, 0, 0));
        txtstock.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtstock.setForeground(new java.awt.Color(255, 255, 255));
        txtstock.setPreferredSize(new java.awt.Dimension(235, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel4.add(txtstock, gridBagConstraints);

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/motorbike256.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel5.add(jLabel6, gridBagConstraints);

        txtcari.setBackground(new java.awt.Color(0, 0, 0));
        txtcari.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtcari.setForeground(new java.awt.Color(255, 255, 255));
        txtcari.setPreferredSize(new java.awt.Dimension(225, 40));
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        jPanel5.add(txtcari, gridBagConstraints);

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass-search.png"))); // NOI18N
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel5.add(btncari, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 128));

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setMaximumSize(new java.awt.Dimension(2147483647, 450));
        jTable2.setPreferredSize(new java.awt.Dimension(300, 1000));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnedit.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette-outline-with-rounded-edges.png"))); // NOI18N
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel3.add(btnedit);

        btnhapus.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus);

        btncancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btncancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelMouseExited(evt);
            }
        });
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtqtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String sql = "SELECT harga FROM suku_cadang WHERE kode_barang = '" +txtkode_barang.getText()+ "'";
                rs = sta.executeQuery(sql);
                if (rs.next()) {
                    String harga = rs.getString("harga");
                    int harga1 = Integer.parseInt(harga);
                    int qty = Integer.parseInt(txtqty.getText());

                    int sub_total = qty*harga1;
                    String harga_akhir = String.valueOf(sub_total);
                    txtharga.setText(harga_akhir);
                    txtharga.requestFocus(true);
                }

            } catch (Exception e) {
            }
            //            btntambahActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press"+ ""));
        }
    }//GEN-LAST:event_txtqtyKeyPressed

    private void txtqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyTyped

    }//GEN-LAST:event_txtqtyKeyTyped

    private void txthargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyPressed
        
    }//GEN-LAST:event_txthargaKeyPressed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btncariActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press"+ ""));
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        //         TableRowSorter sorter = new TableRowSorter(jTable2.getModel());
        //        jTable2.setRowSorter(sorter);
        //        sorter.setRowFilter(RowFilter.regexFilter(Pattern.compile("(?i).*"+ txtcari.getText()+".*",Pattern.CASE_INSENSITIVE | Pattern.DOTALL).toString()));
        //        jTable2.setSelectionMode(1);
        masuktable_suku();
    }//GEN-LAST:event_btncariActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        txtqty.setText("");
        txtharga.setText("");
        txtqty.requestFocus(true);
        txtkode_barang.setText(tbm.getValueAt(jTable2.getSelectedRow(), 0)+"");
        txtnama_barang.setText(tbm.getValueAt(jTable2.getSelectedRow(), 1)+"");
        txtstock.setText(tbm.getValueAt(jTable2.getSelectedRow(), 4)+"");
    }//GEN-LAST:event_jTable2MouseClicked

    private void btncancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseEntered
        btncancel.setText("REFRESH");
    }//GEN-LAST:event_btncancelMouseEntered

    private void btncancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelMouseExited
        btncancel.setText("");
    }//GEN-LAST:event_btncancelMouseExited

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditMouseClicked

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        btnedit.setText("EDIT");
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        btnedit.setText("");
    }//GEN-LAST:event_btneditMouseExited

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Yakin Ingin Merubah Data", "EDIT DATA",
                        JOptionPane.YES_NO_OPTION);
                //dibuat untuk melakukan konfirmasi
                if (confirmed == JOptionPane.YES_OPTION) {
                    try {
                            String sql2 ="SELECT * FROM suku_cadang WHERE kode_barang='" +lblkode.getText()+ "'";
                            rs= sta.executeQuery(sql2);
                            if (rs.next()) {
                                    int stock = Integer.valueOf(rs.getString("stock"));
                                    int hasil = stock+1;
                    
                                    String sql3 = "UPDATE suku_cadang SET stock = '" +hasil+ "' WHERE kode_barang='" +lblkode.getText()+ "'";
                                    sta.executeUpdate(sql3);
                    
                                }
                            String sql = "UPDATE detail_transaksi SET kode_barang='" +txtkode_barang.getText()+ "',qty='" +txtqty.getText()+ "', sub_total='" +txtharga.getText()+ "' WHERE id_detail_transaksi = '" +lblid_detail_transaksi.getText()+ "'";
                            sta.executeUpdate(sql);
                
                            JOptionPane.showMessageDialog(rootPane, "BERHASIL");
                            this.dispose();
                
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }}
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
                        "Yakin Ingin Menghapus Data", "HAPUS DATA",
                        JOptionPane.YES_NO_OPTION);
                //dibuat untuk melakukan konfirmasi
                if (confirmed == JOptionPane.YES_OPTION) {
                    try {
                            String sql2 ="SELECT * FROM suku_cadang WHERE kode_barang='" +lblkode.getText()+ "'";
                            rs= sta.executeQuery(sql2);
                            if (rs.next()) {
                                    int stock = Integer.valueOf(rs.getString("stock"));
                                    int hasil = stock+1;
                    
                                    String sql3 = "UPDATE suku_cadang SET stock = '" +hasil+ "' WHERE kode_barang='" +lblkode.getText()+ "'";
                                    sta.executeUpdate(sql3);
                    
                                }
                            JOptionPane.showMessageDialog(rootPane, "BERHASIL");
                            
                            String sql = "DELETE FROM detail_transaksi WHERE id_detail_transaksi='" +lblid_detail_transaksi.getText()+ "'";
                            sta.executeUpdate(sql);
                            this.dispose();
                
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }
                }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Barang_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Barang_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Barang_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Barang_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Barang_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblid_detail_transaksi;
    private javax.swing.JLabel lblkode;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode_barang;
    private javax.swing.JTextField txtnama_barang;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
static public class HeaderColor extends DefaultTableCellRenderer {
       public HeaderColor(){
           setOpaque(true);
       }   
       public Component getTableCellRendererComponent(JTable jTable2, Object value, boolean selected, boolean focused, int row, int column) { 
        super.getTableCellRendererComponent(jTable2, value, selected, focused, row, column);
           setBackground(Color.black);
           return this;
       }
    }
}
