
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MF
 */
public class Hutang extends javax.swing.JFrame {
   Dimension screensize;
   Connection con;
    Statement sta;
    ResultSet rs;
    DefaultTableModel tbm;
    /**
     * Creates new form Hutang
     */
    public Hutang() {
        initComponents();
        
        btnbayar.setBackground(Color.black);
        txtjumlah_pembayaran.setEditable(false);
        txtkonsumen.setEditable(false);
        txtsisa_pembayaran.setEditable(false);
        txttotal_transaksi.setEditable(false);
        
        screensize = Toolkit.getDefaultToolkit().getScreenSize();
          setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
          
         koneksi DB = new koneksi();
         DB.config();
         con = DB.con;
         sta = DB.stm;
        
    }
    
    public JTextField gettxtnm_kosumen() {
        return txtkonsumen;
    }
    public JTextField gettxttotal() {
        return txttotal_transaksi;
    }
    public JTextField gettxttotal_pembayaran() {
        return txtjumlah_pembayaran;
    }
    public JTextField gettxtsisa_pembayaran() {
        return txtsisa_pembayaran;
    }
    public JLabel getlbl_notransaksi() {
        return lblnotransaksi;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblnotransaksi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkonsumen = new javax.swing.JTextField();
        txttotal_transaksi = new javax.swing.JTextField();
        txtjumlah_pembayaran = new javax.swing.JTextField();
        txtsisa_pembayaran = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnbayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(431, 459));
        setPreferredSize(new java.awt.Dimension(431, 459));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBAYARAN HUTANG");
        jLabel1.setPreferredSize(new java.awt.Dimension(187, 48));
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 5));

        lblnotransaksi.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblnotransaksi.setForeground(new java.awt.Color(255, 255, 255));
        lblnotransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coin32.png"))); // NOI18N
        lblnotransaksi.setText("jLabel2");
        lblnotransaksi.setPreferredSize(new java.awt.Dimension(100, 45));
        jPanel5.add(lblnotransaksi);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA KONSUMEN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL TRANSAKSI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUMLAH PEMBAYARAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SISA PEMBAYARAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(jLabel6, gridBagConstraints);

        txtkonsumen.setBackground(new java.awt.Color(0, 0, 0));
        txtkonsumen.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtkonsumen.setForeground(new java.awt.Color(255, 255, 255));
        txtkonsumen.setPreferredSize(new java.awt.Dimension(190, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 13, 18);
        jPanel2.add(txtkonsumen, gridBagConstraints);

        txttotal_transaksi.setBackground(new java.awt.Color(0, 0, 0));
        txttotal_transaksi.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txttotal_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        txttotal_transaksi.setPreferredSize(new java.awt.Dimension(190, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 13, 18);
        jPanel2.add(txttotal_transaksi, gridBagConstraints);

        txtjumlah_pembayaran.setBackground(new java.awt.Color(0, 0, 0));
        txtjumlah_pembayaran.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtjumlah_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        txtjumlah_pembayaran.setPreferredSize(new java.awt.Dimension(190, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 13, 18);
        jPanel2.add(txtjumlah_pembayaran, gridBagConstraints);

        txtsisa_pembayaran.setBackground(new java.awt.Color(0, 0, 0));
        txtsisa_pembayaran.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtsisa_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        txtsisa_pembayaran.setPreferredSize(new java.awt.Dimension(190, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 13, 18);
        jPanel2.add(txtsisa_pembayaran, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnbayar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnbayar.setForeground(new java.awt.Color(255, 255, 255));
        btnbayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/give-money.png"))); // NOI18N
        btnbayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbayarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbayarMouseExited(evt);
            }
        });
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });
        jPanel3.add(btnbayar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbayarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbayarMouseEntered
        btnbayar.setText("BAYAR");
    }//GEN-LAST:event_btnbayarMouseEntered

    private void btnbayarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbayarMouseExited
        btnbayar.setText("");
    }//GEN-LAST:event_btnbayarMouseExited

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        try {
            String sql;
            sql = ("UPDATE transaksi SET besar_transaksi='" +txttotal_transaksi.getText()+ "',status='TUNAI' WHERE no_transaksi='" +lblnotransaksi.getText()+ "'");
             sta.executeUpdate(sql);
             this.dispose();
        } catch (Exception e) {
             System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hutang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblnotransaksi;
    private javax.swing.JTextField txtjumlah_pembayaran;
    private javax.swing.JTextField txtkonsumen;
    private javax.swing.JTextField txtsisa_pembayaran;
    private javax.swing.JTextField txttotal_transaksi;
    // End of variables declaration//GEN-END:variables
}
