
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Pattern;
import javafx.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MF
 */
public class Merk extends javax.swing.JFrame {
    Connection con;
    Statement sta;
    ResultSet rs;
    DefaultTableModel tbm;
    private final Dimension screensize;
    /**
     * Creates new form Merk
     */
    public Merk() {
        initComponents();
        
        tbl_merk.getTableHeader().setDefaultRenderer(new Supplier.HeaderColor());
        
        btntambah.setBackground(Color.black);
        btnhapus.setBackground(Color.black);
        btnedit.setBackground(Color.black);
        btncari_merk.setBackground(Color.black);
        btnback.setContentAreaFilled(false);
        
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        
        txtnamamerk.requestFocus(true);
        
        screensize = Toolkit.getDefaultToolkit().getScreenSize();
          setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        sta = DB.stm;
        
        autonomor_merk();
        masuktable_merk();
    }
    
    private void masuktable_merk() {
        try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("ID MERK");
                tbm.addColumn("NAMA MERK");
                tbm.addColumn("KET");
                
                tbl_merk.setModel(tbm);
                rs = sta.executeQuery("SELECT * FROM merk_barang");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("id_merk"),
                    rs.getString("nm_merk"),
                    rs.getString("ket"),
                    
                    
                });
                    tbl_merk.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    private void autonomor_merk(){
        String sql = "select max(id_merk) from merk_barang";
        try{
            rs = sta.executeQuery(sql);
            while (rs.next()){
                int a = rs.getInt(1);
                txtidmerk.setText(""+ Integer.toString(a+1));
            }
        }catch (Exception e){
            System.out.println(""+ e.getMessage());
        }

 }
    
    private void kosong_merk() {
        txtnamamerk.setText("");
        txtketmerk.setText("");
        txtnamamerk.requestFocus(true);
        autonomor_merk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidmerk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnamamerk = new javax.swing.JTextField();
        txtketmerk = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtcari_merk = new javax.swing.JTextField();
        btncari_merk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_merk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(537, 463));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel5.add(btnback);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MERK BARANG");
        jPanel5.add(jLabel2);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btntambah.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntambahMouseExited(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel11.add(btntambah);

        btnedit.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette-outline-with-rounded-edges.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel11.add(btnedit);

        btnhapus.setBackground(new java.awt.Color(51, 51, 51));
        btnhapus.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhapusMouseExited(evt);
            }
        });
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel11.add(btnhapus);

        btnbatal.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
        });
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel11.add(btnbatal);

        getContentPane().add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setMinimumSize(new java.awt.Dimension(450, 50));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID MERK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 0, 19);
        jPanel10.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KET");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 0, 19);
        jPanel10.add(jLabel6, gridBagConstraints);

        txtidmerk.setBackground(new java.awt.Color(0, 0, 0));
        txtidmerk.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtidmerk.setForeground(new java.awt.Color(255, 255, 255));
        txtidmerk.setPreferredSize(new java.awt.Dimension(90, 38));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 41, 17, 41);
        jPanel10.add(txtidmerk, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAMA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 0, 19);
        jPanel10.add(jLabel8, gridBagConstraints);

        txtnamamerk.setBackground(new java.awt.Color(0, 0, 0));
        txtnamamerk.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtnamamerk.setForeground(new java.awt.Color(255, 255, 255));
        txtnamamerk.setPreferredSize(new java.awt.Dimension(200, 38));
        txtnamamerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamamerkKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 41, 17, 41);
        jPanel10.add(txtnamamerk, gridBagConstraints);

        txtketmerk.setBackground(new java.awt.Color(0, 0, 0));
        txtketmerk.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtketmerk.setForeground(new java.awt.Color(255, 255, 255));
        txtketmerk.setText("-");
        txtketmerk.setPreferredSize(new java.awt.Dimension(200, 38));
        txtketmerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketmerkActionPerformed(evt);
            }
        });
        txtketmerk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtketmerkKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 41, 17, 41);
        jPanel10.add(txtketmerk, gridBagConstraints);

        jPanel1.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setMinimumSize(new java.awt.Dimension(308, 250));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man-with-company128.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel4.add(jLabel3, gridBagConstraints);

        txtcari_merk.setBackground(new java.awt.Color(0, 0, 0));
        txtcari_merk.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtcari_merk.setForeground(new java.awt.Color(255, 255, 255));
        txtcari_merk.setPreferredSize(new java.awt.Dimension(150, 38));
        txtcari_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari_merkActionPerformed(evt);
            }
        });
        txtcari_merk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcari_merkKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 2, 20, 2);
        jPanel4.add(txtcari_merk, gridBagConstraints);

        btncari_merk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass-search.png"))); // NOI18N
        btncari_merk.setPreferredSize(new java.awt.Dimension(62, 38));
        btncari_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari_merkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        jPanel4.add(btncari_merk, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 150));

        tbl_merk.setBackground(new java.awt.Color(51, 51, 51));
        tbl_merk.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        tbl_merk.setForeground(new java.awt.Color(255, 255, 255));
        tbl_merk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_merk.setPreferredSize(new java.awt.Dimension(300, 250));
        tbl_merk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_merkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_merk);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamamerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamamerkKeyPressed
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            btntambahActionPerformed(new java.awt.event.ActionEvent(evt.getSource(), evt.getID(), "Key Press"+ ""));
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamamerkKeyPressed

    private void txtcari_merkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcari_merkKeyPressed
      if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            btncari_merkActionPerformed(new java.awt.event.ActionEvent(evt.getSource(), evt.getID(), "Key Press"+ ""));
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcari_merkKeyPressed

    private void btncari_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari_merkActionPerformed
        TableRowSorter sorter = new TableRowSorter(tbl_merk.getModel());
        tbl_merk.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(Pattern.compile("(?i).*"+ txtcari_merk.getText()+".*",Pattern.CASE_INSENSITIVE | Pattern.DOTALL).toString()));
        tbl_merk.setSelectionMode(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncari_merkActionPerformed

    private void tbl_merkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_merkMouseClicked
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        btntambah.setEnabled(false);

        txtidmerk.setText(tbm.getValueAt(tbl_merk.getSelectedRow(), 0)+"");
        txtnamamerk.setText(tbm.getValueAt(tbl_merk.getSelectedRow(), 1)+"");
        txtketmerk.setText(tbm.getValueAt(tbl_merk.getSelectedRow(), 2)+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_merkMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        if (txtnamamerk.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "HARAP ISI SEMUA DATA");
        } else {
            try {
                String sql;
                sql = ("INSERT INTO merk_barang VALUES('" + txtidmerk.getText() + "','" +txtnamamerk.getText()+ "','" + txtketmerk.getText() + "')");
                sta.executeUpdate(sql);

                JOptionPane.showMessageDialog(rootPane, "BERHASIL");

                kosong_merk();
                masuktable_merk();
                this.dispose();
                new Suku_Cadang().setVisible(true);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Yakin Ingin Merubah Data", "EDIT DATA",
            JOptionPane.YES_NO_OPTION);
        //dibuat untuk melakukan konfirmasi
        if (confirmed == JOptionPane.YES_OPTION) {
            try {
                String sql;
                sql = ("UPDATE merk_barang set nm_merk='" +txtnamamerk.getText()+ "', "
                    + "ket = '" +txtketmerk.getText()+ "' WHERE id_merk='" +txtidmerk.getText()+ "'");
                sta.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "BERHASIL DIUBAH");

                kosong_merk();
                masuktable_merk();

                btnedit.setEnabled(false);
                btnhapus.setEnabled(false);
                btntambah.setEnabled(true);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Yakin Ingin Menghapus Data", "HAPUS DATA",
            JOptionPane.YES_NO_OPTION);
        //dibuat untuk melakukan konfirmasi
        if (confirmed == JOptionPane.YES_OPTION) {
            try {
                String sql;
                sql = ("DELETE FROM merk_barang WHERE id_merk='" + txtidmerk.getText() + "'");
                sta.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "BERHASIL DIHAPUS");

                kosong_merk();
                masuktable_merk();

                btnedit.setEnabled(false);
                btnhapus.setEnabled(false);
                btntambah.setEnabled(true);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtcari_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari_merkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcari_merkActionPerformed

    private void txtketmerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketmerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketmerkActionPerformed

    private void txtketmerkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtketmerkKeyPressed
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER) {
            btntambahActionPerformed(new java.awt.event.ActionEvent(evt.getSource(), evt.getID(), "Key Press"+ ""));
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketmerkKeyPressed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
         btnedit.setEnabled(false);
         btnhapus.setEnabled(false);
         kosong_merk();
         
        
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btntambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseEntered
        btntambah.setText("TAMBAH");
    }//GEN-LAST:event_btntambahMouseEntered

    private void btntambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseExited
        btntambah.setText("");
    }//GEN-LAST:event_btntambahMouseExited

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
        btnedit.setText("EDIT");
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
        btnedit.setText("");
    }//GEN-LAST:event_btneditMouseExited

    private void btnhapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseEntered
        btnhapus.setText("HAPUS");
    }//GEN-LAST:event_btnhapusMouseEntered

    private void btnhapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseExited
        btnhapus.setText("");
    }//GEN-LAST:event_btnhapusMouseExited

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
        btnbatal.setText("REFRESH");
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
        btnbatal.setText("");
    }//GEN-LAST:event_btnbatalMouseExited
                                  
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Merk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Merk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari_merk;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_merk;
    private javax.swing.JTextField txtcari_merk;
    private javax.swing.JTextField txtidmerk;
    private javax.swing.JTextField txtketmerk;
    private javax.swing.JTextField txtnamamerk;
    // End of variables declaration//GEN-END:variables
static public class HeaderColor extends DefaultTableCellRenderer {
       public HeaderColor(){
           setOpaque(true);
       }   
       public Component getTableCellRendererComponent(JTable tbl_merk, Object value, boolean selected, boolean focused, int row, int column) { 
        super.getTableCellRendererComponent(tbl_merk, value, selected, focused, row, column);
           setBackground(java.awt.Color.black);
           return this;
       }
    }
}
