
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MF
 */
public class Pemberitahuan extends javax.swing.JFrame {
    Connection con;
    Statement sta;
    ResultSet rs;
    DefaultTableModel tbm;
    /**
     * Creates new form Pemberitahuan
     */
    public Pemberitahuan() {
        initComponents();
        
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        btnback.setContentAreaFilled(false);
        btnpembelian.setBackground(Color.black);
        btnlaporan.setBackground(Color.black);
        
        
        txtid_petugas.setVisible(false);
        txtusername.setVisible(false);
         
         jTable1.getTableHeader().setDefaultRenderer(new Supplier.HeaderColor());
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        sta = DB.stm;
        
        masuktable();
        lbljumlah();
        
    }
    
   
    
    private void masuktable() {
        try{
                sta = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                tbm = new DefaultTableModel();
                tbm.addColumn("KODE BARANG");
                tbm.addColumn("NAMA");
                tbm.addColumn("MERK");
                tbm.addColumn("JENIS");
                tbm.addColumn("STOCK");
                tbm.addColumn("HARGA");
                tbm.addColumn("KET");
                
                jTable1.setModel(tbm);
                rs = sta.executeQuery("SELECT suku_cadang.*,merk_barang.id_merk,merk_barang.nm_merk "
                        + "FROM suku_cadang,merk_barang WHERE suku_cadang.id_merk = merk_barang.id_merk "
                        + "AND stock <= 3");
                while (rs.next()){
                    tbm.addRow(new Object[]{
                    rs.getString("kode_barang"),
                    rs.getString("nm_suku_cadang"),
                    rs.getString("nm_merk"),
                    rs.getString("jenis_suku_cadang"),
                    rs.getString("stock"),
                    rs.getString("harga"),
                    rs.getString("ket"),
                    
                    
                });
                    jTable1.setModel(tbm);
                    }
                }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane,"Gagal"+e);
                        
                    }
    }
    
    private void lbljumlah() {
        try {
            String sql;
            sql = "SELECT COUNT(*) AS 'jumlahnya' FROM suku_cadang WHERE stock <= 3";
            rs = sta.executeQuery(sql);
            if (rs.next()) {
                String jumlah =  rs.getString("jumlahnya");
                lbljumlah_barang.setText("JUMLAH BARANG : "+jumlah);
            }
            
        } catch (Exception e) {
        }
    }
    public JTextField gettxt_username() {
        return txtusername;
    }
   
    public void settxt_username(JTextField txt_username) {
        this.txtusername = txtusername;
    }
   
   public JTextField gettxtid_petugas() {
        return txtid_petugas;
    }  
   
    public void settxtid_petugas(JTextField txt_username) {
        this.txtid_petugas = txtid_petugas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtid_petugas = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btnpembelian = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbljumlah_barang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBERITAHUAN SUKU CADANG");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        txtid_petugas.setPreferredSize(new java.awt.Dimension(50, 35));
        jPanel2.add(txtid_petugas);

        txtusername.setPreferredSize(new java.awt.Dimension(50, 35));
        jPanel2.add(txtusername);

        btnpembelian.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnpembelian.setForeground(new java.awt.Color(255, 255, 255));
        btnpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping.png"))); // NOI18N
        btnpembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpembelianMouseExited(evt);
            }
        });
        btnpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btnpembelian);

        btnlaporan.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnlaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        btnlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlaporanMouseExited(evt);
            }
        });
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        jPanel2.add(btnlaporan);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jScrollPane1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DAFTAR SUKU CADANG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        lbljumlah_barang.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lbljumlah_barang.setForeground(new java.awt.Color(255, 255, 255));
        lbljumlah_barang.setText("JUMLAH BARANG : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        jPanel4.add(lbljumlah_barang, gridBagConstraints);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpembelianActionPerformed
        Pembelian_Barang_V02 a = new Pembelian_Barang_V02();
        a.setVisible(true);
        a.getlblid_petugas().setText(txtid_petugas.getText());
        a.getlblusername().setText(txtusername.getText());
    }//GEN-LAST:event_btnpembelianActionPerformed

    private void btnpembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpembelianMouseEntered
        btnpembelian.setText("PEMB.BARANG");
    }//GEN-LAST:event_btnpembelianMouseEntered

    private void btnpembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpembelianMouseExited
        btnpembelian.setText("");
    }//GEN-LAST:event_btnpembelianMouseExited

    private void btnlaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanMouseEntered
        btnlaporan.setText("PRINT");
    }//GEN-LAST:event_btnlaporanMouseEntered

    private void btnlaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlaporanMouseExited
        btnlaporan.setText("");
    }//GEN-LAST:event_btnlaporanMouseExited

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        try {
            MessageFormat header = new MessageFormat("DAFTAR BELANJA");
            MessageFormat footer = new MessageFormat(":)");
            
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnlaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemberitahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemberitahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemberitahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemberitahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemberitahuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnpembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbljumlah_barang;
    private javax.swing.JTextField txtid_petugas;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
static public class HeaderColor extends DefaultTableCellRenderer {
       public HeaderColor(){
           setOpaque(true);
       }   
       public Component getTableCellRendererComponent(JTable jTable1, Object value, boolean selected, boolean focused, int row, int column) { 
        super.getTableCellRendererComponent(jTable1, value, selected, focused, row, column);
           setBackground(Color.black);
           return this;
       }
    }
}
